# Site settings
title: Glium
email: pierre.krieger1708@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Easy to use and safe OpenGL wrapper in Rust
baseurl: "/glium/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: tomaka

# Build settings
markdown: redcarpet
