(function() {var implementors = {};
implementors['image'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;W&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='image/png/zlib/struct.ZlibEncoder.html' title='image::png::zlib::ZlibEncoder'>ZlibEncoder</a>&lt;W&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;W&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='image/png/deflate/struct.Deflater.html' title='image::png::deflate::Deflater'>Deflater</a>&lt;W&gt;",];implementors['glium'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='glium/struct.Program.html' title='glium::Program'>Program</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='glium/backend/struct.Context.html' title='glium::backend::Context'>Context</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='glium/struct.SyncFence.html' title='glium::SyncFence'>SyncFence</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='glium/struct.LinearSyncFence.html' title='glium::LinearSyncFence'>LinearSyncFence</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='glium/struct.Frame.html' title='glium::Frame'>Frame</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
